version: 1
disable_existing_loggers: false
formatters:
  json:
    (): etl.logging_setup.JsonFormatter
handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: json
    level: INFO
    filename: logs/etl.log
root:
  handlers: [console, file]
  level: INFO
